version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - rabbitmq_shared

  postgres-usuarios:
    image: postgres:15
    container_name: postgres-usuarios
    ports: ["5432:5432"]
    environment:
      POSTGRES_DB: usuarios_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: isaac
    volumes:
      - usuarios_data:/var/lib/postgresql/data
    networks:
      - rabbitmq_shared

  ms-usuarios:
    build: ./ms-usuarios
    container_name: ms-usuarios
    ports: ["3001:3001"]
    env_file: ./ms-usuarios/.env
    depends_on: [postgres-usuarios, rabbitmq]
    networks: [rabbitmq_shared]

  postgres-eventos:
    image: postgres:15
    container_name: postgres-eventos
    ports: ["5433:5432"]
    environment:
      POSTGRES_DB: eventos_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: isaac
    volumes:
      - eventos_data:/var/lib/postgresql/data
    networks:
      - rabbitmq_shared

  ms-eventos:
    build: ./ms-eventos
    container_name: ms-eventos
    ports: ["3002:3002"]
    env_file: ./ms-eventos/.env
    depends_on: [postgres-eventos, rabbitmq]
    networks: [rabbitmq_shared]

  postgres-entradas:
    image: postgres:15
    container_name: postgres-entradas
    ports: ["5434:5432"]
    environment:
      POSTGRES_DB: entradas_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: isaac
    volumes:
      - entradas_data:/var/lib/postgresql/data
    networks:
      - rabbitmq_shared

  ms-entradas:
    build: ./ms-entradas
    container_name: ms-entradas
    ports: ["3003:3003"]
    env_file: ./ms-entradas/.env
    depends_on: [postgres-entradas, rabbitmq]
    networks: [rabbitmq_shared]

  postgres-notificaciones:
    image: postgres:15
    container_name: postgres-notificaciones
    ports: ["5435:5432"]
    environment:
      POSTGRES_DB: notificaciones_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: isaac
    volumes:
      - notificaciones_data:/var/lib/postgresql/data
    networks:
      - rabbitmq_shared

  ms-notificaciones:
    build: ./ms-notificaciones
    container_name: ms-notificaciones
    ports: ["3004:3004"]
    env_file: ./ms-notificaciones/.env
    depends_on: [postgres-notificaciones, rabbitmq]
    networks: [rabbitmq_shared]

  postgres-asistencia:
    image: postgres:15
    container_name: postgres-asistencia
    ports: ["5436:5432"]
    environment:
      POSTGRES_DB: asistencia_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: isaac
    volumes:
      - asistencia_data:/var/lib/postgresql/data
    networks:
      - rabbitmq_shared

  ms-asistencia:
    build: ./ms-asistencia
    container_name: ms-asistencia
    ports: ["3005:3005"]
    env_file: ./ms-asistencia/.env
    depends_on: [postgres-asistencia, rabbitmq]
    networks: [rabbitmq_shared]

volumes:
  usuarios_data:
  eventos_data:
  entradas_data:
  notificaciones_data:
  asistencia_data:

networks:
  rabbitmq_shared:
    external: true
    name: notificaciones_default
